openapi: 3.0.3
info:
  version: 0.0.1
  title: (AOS 2023) Entrega diario en taller
  description: API REST para la gestión de los trabajos que se realizan a diario en un taller.
servers:
- url: http://127.0.0.1:80/api/v1
tags:
  - name: Tipos de trabajo
    description: Los diferentes tipos de trabajos que se pueden realizar.
  - name: Trabajo diario
    description: Los trabajos que se pueden realizar a diario en el taller, un trabajo diario corresponde a un tipo de trabajo.
paths:
  /activityTypes:
    get:
      summary: Obtiene todos los tipos de trabajos existentes.
      description: |
          La siguiente tabla define los códigos de estado que puede devolver este endpoint
          (suponer que hay tabla, lol)
          **200** -> OK -> Listado de tipos de trabajo |
          **404** -> NOT_FOUND -> No se encuentra el listado de tipos de trabajo |
      operationId: activityTypes_cget
      tags: [Tipos de trabajo]
      responses:
        '200':
          description: Listado de tipos de trabajo disponibles.
          headers:
            ETag:
              $ref: '#/components/headers/ETag'
          content:
            application/json:
              schema:
                type: object
                properties:
                  tiposTrabajo:
                    description: array de tipos de trabajo
                    type: array
                    items:
                      $ref: '#/components/schemas/TipoTrabajo'
              examples:
                tiposTrabajo-examples:
                  $ref: '#/components/examples/tiposTrabajo-examples'
        '404':
          $ref: '#/components/responses/Response_404'
    options:
      summary: Proporciona la lista de los métodos HTTP soportados por esta ruta.
      description: Devuelve una cabecera `Allow` con la lista de métodos HTTP soportados (separados por comas).
      operationId: plataforma_coptions
      tags: [Tipos de trabajo]
      responses:
        '204':
          description: 'cabecera `Allow` &lt;El cuerpo de la respuesta está vacío&gt;'
          headers:
            Allow:
              $ref: '#/components/headers/Allow'
    post:
      summary: Añade un nuevo tipo de trabajo
      description: |
        La siguiente tabla define los códigos de estado que puede devolver este endpoint
        
        | Status Code | Descripción          | Motivo                                    |
        | ------------| ---------------------| ------------------------------------------|
        | **201**     | CREATED              | El tipo de trabajo ha sido creado              |
        | **400**     | BAD REQUEST          | El identificador único ya existe          |
        | **422**     | UNPROCESSABLE ENTITY | Falta alguno de los atributos obligatorios|
        |             |                      | o el valor no está permitido              |
      tags: [Tipos de trabajo]
      operationId: plataforma_post
      requestBody:
        $ref: '#/components/requestBodies/tipoTrabajoRB'
      responses:
        '201':
          description: Nueva Plataforma creada
          headers:
            Location:
              $ref: '#/components/headers/Location'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TipoTrabajo'
        '400':
          $ref: '#/components/responses/Response_400'
        '422':
          $ref: '#/components/responses/Response_422'
  
  /activityTypes/{IdTipoActividad}:
    parameters:
      - $ref: '#/components/parameters/IdTipoTrabajo'
    options:
      summary: Proporciona la lista de los métodos HTTP soportados por esta ruta.
      description: Devuelve una cabecera `Allow` con la lista de métodos HTTP soportados (separados por comas).
      operationId: plataforma_options
      tags: [Tipos de trabajo]
      responses:
        '204':
          description: 'cabecera `Allow` &lt;El cuerpo de la respuesta está vacío&gt;'
          headers:
            Allow:
              $ref: '#/components/headers/Allow'
    get:
      summary: Obtiene el tipo de trabajo identificado por `IdTipoActividad`.
      description: |
        La siguiente tabla define los códigos de estado que puede devolver este endpoint
        
        | Status Code | Descripción | Motivo                             |
        | ------------| ------------| -----------------------------------|
        | **200**     | OK          | Si el tipo de trabajo existe           |
        | **404**     | NOT FOUND   | Si el tipo de trabajo no existe         |
      operationId: tipoTrabajo_cget
      tags: [Tipos de trabajo]
      responses:
        '200':
          description: Plataforma
          headers:
            ETag:
              $ref: '#/components/headers/ETag'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TipoTrabajo'
        '404':
          $ref: '#/components/responses/Response_404'
    delete:
      summary: Elimina el tipo de trabajo identificado por `IdTipoTrabajo`.
      description: |
        La siguiente tabla define los códigos de estado que puede devolver este endpoint
        
        | Status Code      | Descripción | Motivo                                    |
        | ---------------- | ------------| ------------------------------------------|
        | **204**          | NO CONTENT  | El tipo de trabajo existía y ha sido eliminado |
        | **404**          | NOT FOUND   | Si el tipo de trabajo no existe                |
      operationId: tipoTrabajo_delete
      tags: [Tipos de trabajo]
      responses:
        '204':
          description: Tipo de trabajo eliminado &lt;Cuerpo de la respuesta vacío&gt;
        '404':
          $ref: '#/components/responses/Response_404'
    put:
      tags: [Tipos de trabajo]
      summary: Modifica el tipo de trabajo identificado por `IdTipoTrabajo`.
      description:  |
        La siguiente tabla define los códigos de estado que puede devolver este endpoint
        | Status Code | Descripción         | Motivo                                        |
        | ------------| --------------------| ----------------------------------------------|
        | **209**     | CONTENT RETURNED    | El tipo de trabajo existe y ha sido modificado   |
        | **404**     | NOT FOUND           | Si el tipo de trabajo no existe                   |
        | **412**     | PRECONDITION FAILED | Si el ETag proporcionado no está actualizado  |
        | **422**     | UNPROCESSABLE ENTITY| Valor no permitido en alguno de los attributos|
      operationId: plataforma_put
      parameters:
        - $ref: '#/components/parameters/ifMatchParam'
      requestBody:
        $ref: '#/components/requestBodies/tipoTrabajoUpdate'
      responses:
        '209':
          description: '`CONTENT RETURNED`: El tipo de trabajo ha sido actualizado'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TipoTrabajo'
        '404':
          $ref: '#/components/responses/Response_404'
        '412':
          $ref: '#/components/responses/Response_412'
        '422':
          $ref: '#/components/responses/Response_422'

  /carActivities{CarVIN}:
    parameters:
      - $ref: "#/components/parameters/CarVIN"
    options:
      summary: Proporciona la lista de los métodos HTTP soportados por esta ruta.
      description: Devuelve una cabecera `Allow` con la lista de métodos HTTP soportados (separados por comas).
      operationId: car_activities_options
      tags: [Trabajo diario]
      responses:
        '204':
          description: 'cabecera `Allow` &lt;El cuerpo de la respuesta está vacío&gt;'
          headers:
            Allow:
              $ref: '#/components/headers/Allow'
    get:
      summary: Obtiene los trabajos asociados al vehículo identificado por `CarVIN`.
      description: |
        La siguiente tabla define los códigos de estado que puede devolver este endpoint
        
        | Status Code | Descripción | Motivo                             |
        | ------------| ------------| -----------------------------------|
        | **200**     | OK          | Si el vehículo existe            |
        | **404**     | NOT FOUND   | Si no existe el vehículo        |
      operationId: car_activities_cget
      tags: [Trabajo diario]
      responses:
        '200':
          description: Trabajo diario
          headers:
            ETag:
              $ref: '#/components/headers/ETag'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrabajoDiario'
        '404':
          $ref: '#/components/responses/Response_404'

components:
  schemas:
    TipoTrabajo:
      title: Tipo de trabajo
      description: >
        Tipo de trabajo realizado en un taller que puede ser realizado para 
        cierto tipo de vehículos. 
      type: object
      properties:
        tipoTrabajo:
          type: object
          required: [IdTipoTrabajo, NombreTrabajo, DescripcionTrabajo]
          properties:
            IdTipoTrabajo:
              $ref: '#/components/schemas/IdTipoTrabajo'
            NombreTrabajo:
              $ref: '#/components/schemas/NombreTrabajo'
            DescripcionTrabajo:
              $ref: '#/components/schemas/DescripcionTrabajo'
          example: { "tipoTrabajo" : { "IdTipoTrabajo": "0991",
                                 "NombreTrabajo": "Revisión de fluídos", 
                                 "DescripcionTrabajo": "Comprobación de los niveles de aceite del motor, refrigerante, líquido de frenos, etc"}}

    TrabajoDiario:
      title: Trabajo diario
      description: >
        Trabajo realizado a un vehículo en específico. Pertenece a un tipo de trabajo
      type: object
      properties:
        trabajoDiario:
          type: object
          required: [IdTrabajoDiario, IdTipoTrabajo, NombreTrabajo, DescripcionTrabajo,
                      MotivoTrabajo, FechaInicio, HorasDedicadas, FechaFin,
                      RecursosNecesarios, EstadoTrabajo, VINCoche]
          properties:
            IdTrabajoDiario:
              $ref: '#/components/schemas/IdTrabajoDiario'
            IdTipoTrabajo:
              $ref: '#/components/schemas/IdTipoTrabajo'
            NombreTrabajo:
              $ref: '#/components/schemas/NombreTrabajo'
            DescripcionTrabajo:
              $ref: '#/components/schemas/DescripcionTrabajo'
            MotivoTrabajo:
              $ref: '#/components/schemas/MotivoTrabajo'
            FechaInicio:
              $ref: '#/components/schemas/FechaInicio'
            HorasDedicadas:
              $ref: '#/components/schemas/HorasDedicadas'
            FechaFin:
              $ref: '#/components/schemas/FechaFin'
            RecursosNecesarios:
              $ref: '#/components/schemas/RecursosNecesarios'
            EstadoTrabajo:
              $ref: '#/components/schemas/EstadoTrabajo'
            VINCoche:
              $ref: '#/components/schemas/VINCoche'
          example: { "tipoTrabajo" : { "IdTrabajoDiario": "123",
                                 "IdTipoTrabajo": "0991",
                                 "NombreTrabajo": "Revisión de fluídos", 
                                 "DescripcionTrabajo": "Comprobación de los niveles de aceite del motor, refrigerante, líquido de frenos, etc",
                                 "MotivoTrabajo": "El cliente alega que su vehículo muestra un indicador en su testigo de anomalía en el nivel de aceite",
                                 "FechaInicio": "09/03/2023",
                                 "HorasDedicadas": "2.5",
                                 "FechaFin": "10/03/2023",
                                 "RecursosNecesarios": {
                                                          "IdRecurso1": "214123",
                                                          "IdRecurso2": "3123"},
                                 "EstadoTrabajo": "FINALIZADO",
                                 "VINCoche": "MNCLSFE405W491230"}}

    IdTrabajoDiario:
      type: number
      title: Identificador de un trabajo diario.

    MotivoTrabajo:
      type: string
      title: Descripción del motivo de realización del trabajo.

    FechaInicio:
      type: string
      title: Fecha de entrega del vehículo al taller. Marca el comienzo del trabajo.

    HorasDedicadas:
      type: number
      title: Horas dedicadas al trabajo para acabarlo.

    FechaFin:
      type: string
      title: Fecha de entrega del vehículo al propietario. Marca la finalización del trabajo.

    RecursosNecesarios:
      type: array
      title: Array de identificadores de los recursos necesarios para realizar el trabajo.

    EstadoTrabajo:
      type: string
      title: Estado actual del trabajo.
      enum: [CREADO, PLANIFICADO, INICIADO, TERMINADO]

    VINCoche:
      title: Identificador de vehículo
      type: string
      pattern: "[0-9A-HJ-RP-Z]"

    IdTipoTrabajo:
      type: number
      title: Identificador del tipo de trabajo.
    
    NombreTrabajo:
      type: string
      title: Nombre descriptivo del tipo de trabajo.

    DescripcionTrabajo:
      type: string
      title: Descripción detallada del tipo de trabajo.

    HTTP_Problem:
      type: object
      externalDocs:
        url: https://tools.ietf.org/html/rfc7807
      description: |
        Problem Details for HTTP APIs
        [https://tools.ietf.org/html/rfc7807](https://tools.ietf.org/html/rfc7807)
      properties:
        type:
          type: string
          format: uri
          description: A URI reference [RFC3986] that identifies the problem type
        title:
          type: string
          description: short human-readable summary of the problem type
        status:
          type: number
          description: HTTP status code
        detail:
          type: string
          description: Human-readable explanation specific to this occurrence of the problem
        instance:
          type: string
          format: uri
          description: >
            A URI reference that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.  
  
  headers:
    ETag:
      description: "Entity Tag (identificador único proporcionado para validación de caché)"
      schema:
        type: string
        pattern: "[0-9a-f]"
        example: 21a6712f551bd25fae
    Allow:
      description: Lista de métodos HTTP soportados
      schema:
        type: string
      example: GET, DELETE, PUT, OPTIONS
    Location:
      description: '`URI` del nuevo recurso'
      schema:
        type: string
        format: uri
        x-faker: internet.url
        example:
          https://example.com/api/v1/tiposTrabajo/0991

  examples:
    tiposTrabajo-examples:
      value:
        - { "tipoTrabajo" : { "IdTipoTrabajo": "0991",
                                 "NombreTrabajo": "Revisión de fluídos", 
                                 "DescripcionTrabajo": "Comprobación de los niveles de aceite del motor, refrigerante, líquido de frenos, etc"}}
        - { "tipoTrabajo" : { "IdTipoTrabajo": "0992",
                                 "NombreTrabajo": "Limpieza de motor", 
                                 "DescripcionTrabajo": "Limpieza interna y externa del motor"}}
    response-http-400:
      value:
        type: https://httpstatuses.com/400
        title: UNPROCESSABLE ENTITY
        status: 400
        detail: El identificador único ya existe
        instance: about:blank
    response-http-404:
      value:
        type: https://httpstatuses.com/404
        title: NOT FOUND
        status: 404
        detail: El recurso solicitado no está disponible.
        instance: about:blank
    response-http-412:
      value:
        type: https://httpstatuses.com/412
        title: PRECONDITION FAILED
        status: 412
        detail: El ETag proporcionado no está actualizado
        instance: about:blank
    response-http-422:
      value:
        type: https://httpstatuses.com/422
        title: UNPROCESSABLE ENTITY
        status: 422
        detail: Falta alguno de los atributos obligatorios o contiene un valor no admitido
        instance: about:blank


  responses:
    Response_400:
      description: '`BAD REQUEST` El identificador único ya existe.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-400:
              $ref: '#/components/examples/response-http-400'
    Response_404:
      description: '`NOT FOUND`: Recurso no disponible'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-404:
              $ref: '#/components/examples/response-http-404'
    Response_412:
      description: '`PRECONDITION FAILED`: El ETag proporcionado no está actualizado'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-412:
              $ref: '#/components/examples/response-http-412'
    Response_422:
      description: '`UNPROCESSABLE ENTITY` Falta alguno de los atributos obligatorios o son incorrectos.'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-422:
              $ref: '#/components/examples/response-http-422'

  requestBodies:
    tipoTrabajoRB:
      description: Información de nuevo tipo de trabajo
      required: true
      content:
        application/json:
          schema:
            type: object
            required: [IdTipoTrabajo, NombreTrabajo, DescripcionTrabajo]
            properties:
              IdTipoTrabajo:
                $ref: '#/components/schemas/IdTipoTrabajo'
              NombreTrabajo:
                $ref: '#/components/schemas/NombreTrabajo'
              DescripcionTrabajo:
                $ref: '#/components/schemas/DescripcionTrabajo'
    tipoTrabajoUpdate:
      description: Nuevos atributos del tipo de trabajo
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              NombreTrabajo:
                $ref: '#/components/schemas/NombreTrabajo'
              DescripcionTrabajo:
                $ref: '#/components/schemas/DescripcionTrabajo'
          example: { "NombreTrabajo": "Nuevo nombre de tipo de trabajo", "DescripcionTrabajo": "Nueva descripcion de tipo de trabajo" }
  
  parameters:
    IdTipoTrabajo:
      name: plataforma_id
      in: path
      description: Identificador único de la Plataforma
      required: true
      schema:
        $ref: '#/components/schemas/IdTipoTrabajo'
    ifMatchParam:
      name: If-Match
      in: header
      description: ETag actual del recurso que se desea modificar
      required: true
      schema:
        type: string
        pattern: "[0-9a-f]*"
    CarVIN:
      name: CarVIN
      in: path
      description: Idetificador de un vehículo
      required: true
      schema:
        $ref: '#/components/schemas/VINCoche'