apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mock-backendtrabajos
  name: mock-backendtrabajos
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mock-backendtrabajos
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/aosmicroservicio-grupo1-default: "true"
        io.kompose.service: mock-backendtrabajos
    spec:
      containers:
        - args:
            - mock
            - --cors
            - -h
            - 0.0.0.0
            - /aos/openapi.yaml
          image: stoplight/prism:latest
          name: aos2023trabajos-mock
          ports:
            - containerPort: 4010
          resources: {}
          volumeMounts:
            - mountPath: /aos
              name: mock-backendtrabajos-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: mock-backendtrabajos-claim0
          persistentVolumeClaim:
            claimName: mock-backendtrabajos-claim0
            readOnly: true
status: {}
