apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: proxylogs
  name: proxylogs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxylogs
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/aosmicroservicio-grupo1-default: "true"
        io.kompose.service: proxylogs
    spec:
      containers:
        - image: caddy:latest
          name: aos2023-proxy
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /etc/caddy/Caddyfile
              name: proxylogs-claim0
            - mountPath: /data
              name: proxylogs-claim1
      restartPolicy: Always
      volumes:
        - name: proxylogs-claim0
          persistentVolumeClaim:
            claimName: proxylogs-claim0
        - name: proxylogs-claim1
          persistentVolumeClaim:
            claimName: proxylogs-claim1
status: {}
